package com.kareem.ntake
import android.Manifest
import android.content.Intent
import android.content.pm.PackageManager
import android.media.MediaRecorder
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.graphics.*
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.*
import androidx.core.content.ContextCompat
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.google.mlkit.vision.common.InputImage
import com.google.mlkit.vision.text.TextRecognition
import com.google.mlkit.vision.text.latin.TextRecognizerOptions
import java.io.File
import java.text.DateFormat
import java.util.Date
private val Ink=Color(0xFF071017);private val Surface=Color(0xFF101B24);private val Surface2=Color(0xFF162632);private val Mint=Color(0xFF6FE1D0);private val Violet=Color(0xFF9A7CFF);private val Blue=Color(0xFF5C8DFF);private val Warm=Color(0xFFFFB86B)
class MainActivity:ComponentActivity(){private var recorder:MediaRecorder?=null
 override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{NtakeTheme{NtakeAppUi((application as NtakeApp).repo,this)}}}
 fun startRecording():File{val f=File(filesDir,"voice_"+System.currentTimeMillis()+".m4a");recorder=MediaRecorder(this).apply{setAudioSource(MediaRecorder.AudioSource.MIC);setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);setAudioEncoder(MediaRecorder.AudioEncoder.AAC);setOutputFile(f.absolutePath);prepare();start()};return f}
 fun stopRecording(){runCatching{recorder?.stop()};recorder?.release();recorder=null}}
@Composable fun NtakeTheme(content: @Composable () -> Unit){MaterialTheme(colorScheme=darkColorScheme(primary=Mint,secondary=Violet,background=Ink,surface=Surface,onBackground=Color(0xFFF4F7FA),onSurface=Color(0xFFF4F7FA)),content=content)}
@Composable fun NtakeAppUi(repo:NoteRepository,activity:MainActivity){val notes by repo.notes.collectAsStateWithLifecycle();var tab by remember{mutableStateOf("home")};var capture by remember{mutableStateOf<String?>(activity.intent.getStringExtra("capture"))};var selected by remember{mutableStateOf<Note?>(null)};val shared=remember{activity.intent.getStringExtra(Intent.EXTRA_TEXT)}
 LaunchedEffect(shared){if(!shared.isNullOrBlank()){repo.add("Shared note",shared,"SHARE",summary=smartSummary(shared));activity.intent.removeExtra(Intent.EXTRA_TEXT)}}
 Scaffold(containerColor=Ink,bottomBar={NavigationBar(containerColor=Color(0xFF0A141C)){listOf("home" to Icons.Default.Home,"notes" to Icons.Default.Description,"capture" to Icons.Default.AddCircle,"follow" to Icons.Default.Schedule,"search" to Icons.Default.Search).forEach{(k,ic)->NavigationBarItem(selected=tab==k,onClick={if(k=="capture")capture="menu" else tab=k},icon={Icon(ic,k)},label={Text(if(k=="follow")"Follow-ups" else k.replaceFirstChar{it.uppercase()})})}}}){pad->Box(Modifier.padding(pad).fillMaxSize()){when(tab){"home"->Home(notes,{selected=it},{capture="menu"});"notes"->Library(notes){selected=it};"follow"->FollowUps(notes,repo){selected=it};"search"->Search(repo){selected=it}}}}
 if(capture!=null)CaptureSheet(capture!!,activity,repo,{capture=null},{capture=it});selected?.let{NoteDetail(it,onDismiss={selected=null},onResolve={repo.setResolved(it.id);selected=null})}}
@Composable fun Home(notes:List<Note>,open:(Note)->Unit,capture:()->Unit){val loops=notes.count{it.followUp&&it.status!="RESOLVED"};LazyColumn(Modifier.fillMaxSize().padding(horizontal=18.dp),contentPadding=PaddingValues(bottom=24.dp)){item{Spacer(Modifier.height(18.dp));Text("Good morning, Karim 👋",fontSize=27.sp,fontWeight=FontWeight.Bold);Text("Less to remember. More to do.",color=Color.Gray);Spacer(Modifier.height(18.dp));HeroSearch();Spacer(Modifier.height(16.dp));Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Metric("Needs Attention",loops.toString()+" open loops",Warm,Modifier.weight(1f));Metric("Today",notes.size.toString()+" memories",Blue,Modifier.weight(1f))};Spacer(Modifier.height(12.dp));Metric("Connected knowledge","Source-grounded personal memory",Mint,Modifier.fillMaxWidth());Spacer(Modifier.height(22.dp));SectionTitle("Recent captures","See all")};items(notes.take(8)){NoteCard(it){open(it)}};item{Spacer(Modifier.height(12.dp));Button(onClick=capture,modifier=Modifier.fillMaxWidth().height(58.dp),shape=RoundedCornerShape(20.dp)){Icon(Icons.Default.AutoAwesome,null);Spacer(Modifier.width(8.dp));Text("Capture anything",fontWeight=FontWeight.Bold)}}}}
@Composable fun HeroSearch(){Surface(shape=RoundedCornerShape(22.dp),color=Surface2,modifier=Modifier.fillMaxWidth()){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.Search,null,tint=Mint);Spacer(Modifier.width(10.dp));Text("Search your notes, ask anything…",color=Color.LightGray);Spacer(Modifier.weight(1f));Icon(Icons.Default.Mic,null,tint=Violet)}}}
@Composable fun Metric(title:String,sub:String,accent:Color,mod:Modifier){Surface(mod,shape=RoundedCornerShape(22.dp),color=Surface2){Column(Modifier.padding(16.dp)){Box(Modifier.size(9.dp).background(accent,RoundedCornerShape(9.dp)));Spacer(Modifier.height(10.dp));Text(title,fontWeight=FontWeight.Bold);Text(sub,color=Color.LightGray,fontSize=13.sp)}}}
@Composable fun SectionTitle(a:String,b:String){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(a,fontSize=19.sp,fontWeight=FontWeight.Bold);Text(b,color=Mint)};Spacer(Modifier.height(10.dp))}
@OptIn(ExperimentalMaterial3Api::class)
@Composable fun NoteCard(n:Note,onClick:()->Unit){Surface(onClick=onClick,shape=RoundedCornerShape(18.dp),color=Surface2,modifier=Modifier.fillMaxWidth().padding(vertical=5.dp)){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Surface(shape=RoundedCornerShape(14.dp),color=when(n.source){"VOICE"->Violet.copy(.22f);"IMAGE"->Mint.copy(.22f);"LINK"->Warm.copy(.22f);else->Blue.copy(.2f)}){Icon(when(n.source){"VOICE"->Icons.Default.Mic;"IMAGE"->Icons.Default.Image;"LINK"->Icons.Default.Link;else->Icons.Default.Description},null,Modifier.padding(11.dp),tint=Color.White)};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(n.title,fontWeight=FontWeight.SemiBold,maxLines=1,overflow=TextOverflow.Ellipsis);Text(n.summary.ifBlank{n.body},color=Color.LightGray,fontSize=13.sp,maxLines=2,overflow=TextOverflow.Ellipsis)};if(n.followUp)AssistChip(onClick={},label={Text(if(n.status=="RESOLVED")"Resolved" else "Waiting")})}}}
@OptIn(ExperimentalMaterial3Api::class)
@Composable fun CaptureSheet(mode:String,activity:MainActivity,repo:NoteRepository,dismiss:()->Unit,setMode:(String)->Unit){var text by remember{mutableStateOf("")};var recording by remember{mutableStateOf(false)};var audio by remember{mutableStateOf<File?>(null)};var busy by remember{mutableStateOf(false)}
 val mic=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){if(it){audio=activity.startRecording();recording=true}}
 val picker=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){uri:Uri?->if(uri!=null){busy=true;val image=InputImage.fromFilePath(activity,uri);TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS).process(image).addOnSuccessListener{r->val body=r.text.ifBlank{"Image captured — no readable text detected"};repo.add("Image capture",body,"IMAGE",summary=smartSummary(body));busy=false;dismiss()}.addOnFailureListener{repo.add("Image capture","Original image: "+uri,"IMAGE",summary="OCR failed; original reference preserved.");busy=false;dismiss()}}}
 ModalBottomSheet(onDismissRequest={if(recording)activity.stopRecording();dismiss()},containerColor=Surface){Column(Modifier.fillMaxWidth().padding(20.dp)){Text("Capture",fontSize=26.sp,fontWeight=FontWeight.Bold);Text("Anything. We'll make sense of it.",color=Color.Gray);Spacer(Modifier.height(18.dp))
 if(mode=="menu"){Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){CaptureButton("Text",Icons.Default.Edit,Warm){setMode("text")};CaptureButton("Voice",Icons.Default.Mic,Violet){setMode("voice")};CaptureButton("Image",Icons.Default.CameraAlt,Mint){setMode("image")};CaptureButton("Link",Icons.Default.Link,Blue){setMode("link")}}}
 if(mode=="text"||mode=="link"){OutlinedTextField(text,{text=it},label={Text(if(mode=="link")"Paste a URL or thought" else "What's on your mind?")},modifier=Modifier.fillMaxWidth().heightIn(min=150.dp));Spacer(Modifier.height(12.dp));Button(enabled=text.isNotBlank(),onClick={val src=if(mode=="link")"LINK" else "TEXT";repo.add(if(mode=="link")"Saved link" else titleFrom(text),text,src,tags=classify(text),summary=smartSummary(text),followUp=isFollowUp(text));dismiss()},modifier=Modifier.fillMaxWidth()){Text("Save & understand")}}
 if(mode=="voice"){Box(Modifier.fillMaxWidth().height(180.dp),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.GraphicEq,null,Modifier.size(72.dp),tint=Violet);Text(if(recording)"Recording…" else "Ready to record",fontSize=22.sp,fontWeight=FontWeight.Bold)}};Button(onClick={if(recording){activity.stopRecording();repo.add("Voice note","Audio preserved at "+audio?.absolutePath.orEmpty(),"VOICE",summary="Voice recording captured. Transcription provider is not configured in this local build.");recording=false;dismiss()}else if(ContextCompat.checkSelfPermission(activity,Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED){audio=activity.startRecording();recording=true}else mic.launch(Manifest.permission.RECORD_AUDIO)},modifier=Modifier.fillMaxWidth()){Icon(if(recording)Icons.Default.Stop else Icons.Default.Mic,null);Spacer(Modifier.width(8.dp));Text(if(recording)"Stop & save" else "Start recording")}}
 if(mode=="image"){Button(onClick={picker.launch("image/*")},modifier=Modifier.fillMaxWidth().height(64.dp),enabled=!busy){Icon(Icons.Default.Image,null);Spacer(Modifier.width(8.dp));Text(if(busy)"Reading image…" else "Choose image / screenshot")}}}}}
@Composable fun RowScope.CaptureButton(t:String,i:androidx.compose.ui.graphics.vector.ImageVector,c:Color,click:()->Unit){Surface(onClick=click,modifier=Modifier.weight(1f),shape=RoundedCornerShape(18.dp),color=c.copy(.2f)){Column(Modifier.padding(vertical=16.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(i,null,tint=c);Spacer(Modifier.height(6.dp));Text(t,fontSize=12.sp)}}}
@Composable fun Library(notes:List<Note>,open:(Note)->Unit){LazyColumn(Modifier.fillMaxSize().padding(18.dp)){item{Text("All Notes",fontSize=28.sp,fontWeight=FontWeight.Bold);Text(notes.size.toString()+" captured memories",color=Color.Gray);Spacer(Modifier.height(16.dp))};items(notes){NoteCard(it){open(it)}}}}
@Composable fun FollowUps(notes:List<Note>,repo:NoteRepository,open:(Note)->Unit){val list=notes.filter{it.followUp};LazyColumn(Modifier.fillMaxSize().padding(18.dp)){item{Text("Follow-ups",fontSize=28.sp,fontWeight=FontWeight.Bold);Text("Never lose an open loop again.",color=Color.Gray);Spacer(Modifier.height(16.dp))};if(list.isEmpty())item{Empty("No follow-ups yet","Waiting, calling, checking and replying notes become open loops.")};items(list){NoteCard(it){open(it)}}}}
@Composable fun Search(repo:NoteRepository,open:(Note)->Unit){var q by remember{mutableStateOf("")};var results by remember{mutableStateOf(emptyList<Note>())};LaunchedEffect(q){results=repo.search(q)};LazyColumn(Modifier.fillMaxSize().padding(18.dp)){item{Text("Search",fontSize=28.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(12.dp));OutlinedTextField(q,{q=it},leadingIcon={Icon(Icons.Default.Search,null)},placeholder={Text("What was Ahmed's marble price?")},modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(14.dp))};items(results){NoteCard(it){open(it)}}}}
@Composable fun Empty(title:String,sub:String){Surface(shape=RoundedCornerShape(22.dp),color=Surface2){Column(Modifier.padding(22.dp)){Icon(Icons.Default.AutoAwesome,null,tint=Mint);Spacer(Modifier.height(8.dp));Text(title,fontWeight=FontWeight.Bold);Text(sub,color=Color.Gray)}}}
@OptIn(ExperimentalMaterial3Api::class)
@Composable fun NoteDetail(n:Note,onDismiss:()->Unit,onResolve:()->Unit){ModalBottomSheet(onDismissRequest=onDismiss,containerColor=Surface){LazyColumn(Modifier.fillMaxWidth().padding(20.dp),contentPadding=PaddingValues(bottom=36.dp)){item{Row(verticalAlignment=Alignment.CenterVertically){Text(n.title,fontSize=25.sp,fontWeight=FontWeight.Bold,modifier=Modifier.weight(1f));IconButton(onClick=onDismiss){Icon(Icons.Default.Close,null)}};Text(n.source+" • "+DateFormat.getDateTimeInstance(DateFormat.MEDIUM,DateFormat.SHORT).format(Date(n.createdAt)),color=Color.Gray);Spacer(Modifier.height(18.dp));Label("AI Summary");Info(n.summary.ifBlank{"No derived summary. Original source remains preserved."});Spacer(Modifier.height(14.dp));Label("Original / extracted content");Info(n.body);Spacer(Modifier.height(14.dp));Label("Classification");Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){n.tags.split(",").filter{it.isNotBlank()}.forEach{AssistChip(onClick={},label={Text(it)})}};Spacer(Modifier.height(14.dp));Label("Connections");Info("Relationships are grounded in people, projects, topics and explicit follow-up state.");if(n.followUp&&n.status!="RESOLVED"){Spacer(Modifier.height(16.dp));Button(onClick=onResolve,modifier=Modifier.fillMaxWidth()){Icon(Icons.Default.CheckCircle,null);Spacer(Modifier.width(8.dp));Text("Resolve follow-up")}}}}}}
@Composable fun Label(s:String){Text(s,color=Mint,fontWeight=FontWeight.Bold)}
@Composable fun Info(s:String){Surface(shape=RoundedCornerShape(18.dp),color=Surface2,modifier=Modifier.fillMaxWidth()){Text(s,Modifier.padding(16.dp),lineHeight=21.sp)}}
fun titleFrom(s:String)=s.trim().lineSequence().firstOrNull()?.take(52)?.ifBlank{"New note"}?:"New note"
fun smartSummary(s:String):String{val t=s.trim().replace(Regex("\\s+")," ");return if(t.length<=150)t else t.take(147)+"…"}
fun isFollowUp(s:String):Boolean{val x=s.lowercase();return listOf("waiting","follow up","follow-up","call ","reply","tomorrow","مستني","تابع","كلم","بكرة","رد").any{x.contains(it)}}
fun classify(s:String):String{val x=s.lowercase();val out=mutableListOf<String>();if(isFollowUp(s))out+="Follow-up";if(listOf("idea","فكرة").any{x.contains(it)})out+="Idea";if(listOf("price","quotation","سعر","عرض سعر").any{x.contains(it)})out+="Pricing";if(listOf("remind","reminder","فكرني").any{x.contains(it)})out+="Reminder";return out.ifEmpty{listOf("Note")}.joinToString(",")}
